// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sentinel/plan/v1/plan.proto

package v1types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	types1 "github.com/sentinel-official/hub/v12/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Plan struct {
	Id       uint64                                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider string                                   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Price    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=price,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"price"`
	Validity time.Duration                            `protobuf:"bytes,4,opt,name=validity,proto3,stdduration" json:"validity"`
	Bytes    github_com_cosmos_cosmos_sdk_types.Int   `protobuf:"bytes,5,opt,name=bytes,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"bytes"`
	Status   types1.Status                            `protobuf:"varint,6,opt,name=status,proto3,enum=sentinel.types.v1.Status" json:"status,omitempty"`
	StatusAt time.Time                                `protobuf:"bytes,7,opt,name=status_at,json=statusAt,proto3,stdtime" json:"status_at"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21366ce9b6e0371, []int{0}
}
func (m *Plan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return m.Size()
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Plan)(nil), "sentinel.plan.v1.Plan")
}

func init() { proto.RegisterFile("sentinel/plan/v1/plan.proto", fileDescriptor_b21366ce9b6e0371) }

var fileDescriptor_b21366ce9b6e0371 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0x8e, 0xd4, 0x30,
	0x10, 0xc6, 0xe3, 0xfd, 0xc7, 0x9e, 0x91, 0x4e, 0x28, 0xa2, 0xc8, 0x2d, 0x92, 0x13, 0x51, 0xa0,
	0x34, 0x67, 0x93, 0xa5, 0x04, 0x09, 0xdd, 0x72, 0x0d, 0x1d, 0x0a, 0x54, 0x14, 0x20, 0x27, 0xf1,
	0xe6, 0x2c, 0xb2, 0x71, 0x14, 0x3b, 0x16, 0xfb, 0x16, 0x27, 0x2a, 0x1e, 0x01, 0xf1, 0x24, 0x5b,
	0x5e, 0x89, 0x28, 0x6e, 0x61, 0xf7, 0x45, 0x50, 0xec, 0x24, 0x42, 0xd0, 0x5c, 0xe5, 0xb1, 0x67,
	0x3e, 0xfb, 0xf7, 0xcd, 0x18, 0x3e, 0x92, 0xac, 0x54, 0xbc, 0x64, 0x05, 0xa9, 0x0a, 0x5a, 0x12,
	0x1d, 0x99, 0x15, 0x57, 0xb5, 0x50, 0xc2, 0x7d, 0xd0, 0x27, 0xb1, 0x39, 0xd4, 0xd1, 0x02, 0xa5,
	0x42, 0x6e, 0x84, 0x24, 0x09, 0x95, 0x8c, 0xe8, 0x28, 0x61, 0x8a, 0x46, 0x24, 0x15, 0xbc, 0x53,
	0x2c, 0x1e, 0xe6, 0x22, 0x17, 0x26, 0x24, 0x6d, 0xd4, 0x9d, 0xa2, 0x5c, 0x88, 0xbc, 0x60, 0xc4,
	0xec, 0x92, 0x66, 0x4d, 0xb2, 0xa6, 0xa6, 0x8a, 0x8b, 0x5e, 0xe5, 0xff, 0x9b, 0x57, 0x7c, 0xc3,
	0xa4, 0xa2, 0x9b, 0xaa, 0xbf, 0x60, 0xa0, 0x54, 0xdb, 0x8a, 0xc9, 0x16, 0x53, 0x2a, 0xaa, 0x1a,
	0x69, 0xf3, 0x8f, 0xbf, 0x8c, 0xe1, 0xe4, 0x4d, 0x41, 0x4b, 0xf7, 0x14, 0x8e, 0x78, 0xe6, 0x81,
	0x00, 0x84, 0x93, 0x78, 0xc4, 0x33, 0x77, 0x01, 0xe7, 0x55, 0x2d, 0x34, 0xcf, 0x58, 0xed, 0x8d,
	0x02, 0x10, 0x9e, 0xc4, 0xc3, 0xde, 0xa5, 0x70, 0x5a, 0xd5, 0x3c, 0x65, 0xde, 0x38, 0x18, 0x87,
	0xf7, 0x97, 0x67, 0xd8, 0x7a, 0xc3, 0xad, 0x37, 0xdc, 0x79, 0xc3, 0xaf, 0x04, 0x2f, 0x57, 0x4f,
	0x77, 0xb7, 0xbe, 0xf3, 0x7d, 0xef, 0x87, 0x39, 0x57, 0x57, 0x4d, 0x82, 0x53, 0xb1, 0x21, 0x5d,
	0x23, 0xec, 0x72, 0x2e, 0xb3, 0x4f, 0x16, 0xcd, 0x08, 0x64, 0x6c, 0x6f, 0x76, 0x5f, 0xc2, 0xb9,
	0xa6, 0x05, 0xcf, 0xb8, 0xda, 0x7a, 0x93, 0x00, 0x98, 0x57, 0xac, 0x57, 0xdc, 0x7b, 0xc5, 0x97,
	0x5d, 0x2f, 0x56, 0xf3, 0xf6, 0x95, 0xaf, 0x7b, 0x1f, 0xc4, 0x83, 0xc8, 0xbd, 0x84, 0xd3, 0x64,
	0xab, 0x98, 0xf4, 0xa6, 0x2d, 0xfc, 0x0a, 0xb7, 0x25, 0x3f, 0x6f, 0xfd, 0x27, 0x77, 0x00, 0x79,
	0x5d, 0xaa, 0xd8, 0x8a, 0xdd, 0x08, 0xce, 0x6c, 0xbb, 0xbc, 0x59, 0x00, 0xc2, 0xd3, 0xe5, 0x19,
	0x1e, 0x06, 0x6b, 0x6b, 0x75, 0x84, 0xdf, 0x9a, 0x82, 0xb8, 0x2b, 0x74, 0x2f, 0xe0, 0x89, 0x8d,
	0x3e, 0x52, 0xe5, 0xdd, 0x33, 0xe8, 0x8b, 0xff, 0xd0, 0xdf, 0xf5, 0x63, 0xb2, 0xec, 0xd7, 0x86,
	0xdd, 0xca, 0x2e, 0xd4, 0xea, 0xc3, 0xee, 0x37, 0x72, 0xbe, 0x1d, 0x90, 0xb3, 0x3b, 0x20, 0x70,
	0x73, 0x40, 0xe0, 0xd7, 0x01, 0x81, 0xeb, 0x23, 0x72, 0x6e, 0x8e, 0xc8, 0xf9, 0x71, 0x44, 0xce,
	0xfb, 0x17, 0x7f, 0xd9, 0xe8, 0x89, 0xce, 0xc5, 0x7a, 0xcd, 0x53, 0x4e, 0x0b, 0x72, 0xd5, 0x24,
	0x44, 0x47, 0x4b, 0xf2, 0xd9, 0x7e, 0xcd, 0x7e, 0xf2, 0xcf, 0x75, 0x64, 0xc2, 0x64, 0x66, 0x38,
	0x9e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x1e, 0x99, 0x48, 0xc3, 0x02, 0x00, 0x00,
}

func (m *Plan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Plan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Plan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StatusAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StatusAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintPlan(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	if m.Status != 0 {
		i = encodeVarintPlan(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.Bytes.Size()
		i -= size
		if _, err := m.Bytes.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPlan(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.Validity, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Validity):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintPlan(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	if len(m.Price) > 0 {
		for iNdEx := len(m.Price) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Price[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPlan(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintPlan(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintPlan(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPlan(dAtA []byte, offset int, v uint64) int {
	offset -= sovPlan(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Plan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPlan(uint64(m.Id))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovPlan(uint64(l))
	}
	if len(m.Price) > 0 {
		for _, e := range m.Price {
			l = e.Size()
			n += 1 + l + sovPlan(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Validity)
	n += 1 + l + sovPlan(uint64(l))
	l = m.Bytes.Size()
	n += 1 + l + sovPlan(uint64(l))
	if m.Status != 0 {
		n += 1 + sovPlan(uint64(m.Status))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StatusAt)
	n += 1 + l + sovPlan(uint64(l))
	return n
}

func sovPlan(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPlan(x uint64) (n int) {
	return sovPlan(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Plan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Plan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Plan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = append(m.Price, types.Coin{})
			if err := m.Price[len(m.Price)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.Validity, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bytes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bytes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= types1.Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StatusAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPlan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPlan(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPlan
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPlan
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPlan
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPlan
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPlan        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPlan          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPlan = fmt.Errorf("proto: unexpected end of group")
)
