// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sentinel/subscription/v2/payout.proto

package v2

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Payout struct {
	ID          uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address     string     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	NodeAddress string     `protobuf:"bytes,3,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	Hours       int64      `protobuf:"varint,4,opt,name=hours,proto3" json:"hours,omitempty"`
	Price       types.Coin `protobuf:"bytes,5,opt,name=price,proto3" json:"price"`
	NextAt      time.Time  `protobuf:"bytes,6,opt,name=next_at,json=nextAt,proto3,stdtime" json:"next_at"`
}

func (m *Payout) Reset()         { *m = Payout{} }
func (m *Payout) String() string { return proto.CompactTextString(m) }
func (*Payout) ProtoMessage()    {}
func (*Payout) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20b0a92fdfecfe5, []int{0}
}
func (m *Payout) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Payout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Payout.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Payout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payout.Merge(m, src)
}
func (m *Payout) XXX_Size() int {
	return m.Size()
}
func (m *Payout) XXX_DiscardUnknown() {
	xxx_messageInfo_Payout.DiscardUnknown(m)
}

var xxx_messageInfo_Payout proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Payout)(nil), "sentinel.subscription.v2.Payout")
}

func init() {
	proto.RegisterFile("sentinel/subscription/v2/payout.proto", fileDescriptor_f20b0a92fdfecfe5)
}

var fileDescriptor_f20b0a92fdfecfe5 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xbb, 0x8e, 0x9b, 0x40,
	0x14, 0x86, 0x19, 0x6c, 0xe3, 0x64, 0x9c, 0x0a, 0x59, 0x11, 0x71, 0x31, 0x90, 0x48, 0x91, 0x68,
	0x32, 0x23, 0x13, 0xa5, 0x4b, 0x0a, 0x93, 0x34, 0xe9, 0x22, 0x94, 0x2a, 0x45, 0x2c, 0x2e, 0x63,
	0x3c, 0x92, 0xe1, 0x20, 0x66, 0x40, 0xf6, 0x5b, 0xf8, 0x31, 0xf2, 0x28, 0x2e, 0x5d, 0xa6, 0xf2,
	0xee, 0xe2, 0x6a, 0xdf, 0x62, 0x05, 0x18, 0x69, 0xb7, 0x3b, 0x97, 0xef, 0x97, 0xce, 0xa7, 0x83,
	0x3f, 0x4a, 0x9e, 0x2b, 0x91, 0xf3, 0x1d, 0x93, 0x55, 0x24, 0xe3, 0x52, 0x14, 0x4a, 0x40, 0xce,
	0x6a, 0x8f, 0x15, 0xe1, 0x01, 0x2a, 0x45, 0x8b, 0x12, 0x14, 0x98, 0xd6, 0x80, 0xd1, 0xe7, 0x18,
	0xad, 0xbd, 0x05, 0x89, 0x41, 0x66, 0x20, 0x59, 0x14, 0x4a, 0xce, 0xea, 0x65, 0xc4, 0x55, 0xb8,
	0x64, 0x31, 0x88, 0xbc, 0x4f, 0x2e, 0xe6, 0x29, 0xa4, 0xd0, 0x95, 0xac, 0xad, 0x6e, 0x53, 0x3b,
	0x05, 0x48, 0x77, 0x9c, 0x75, 0x5d, 0x54, 0x6d, 0x98, 0x12, 0x19, 0x97, 0x2a, 0xcc, 0x8a, 0x1e,
	0xf8, 0xf0, 0x88, 0xb0, 0xf1, 0xab, 0xbb, 0xc0, 0x7c, 0x8b, 0x75, 0x91, 0x58, 0xc8, 0x41, 0xee,
	0xd8, 0x37, 0x9a, 0x8b, 0xad, 0xff, 0xfc, 0x11, 0xe8, 0x22, 0x31, 0x2d, 0x3c, 0x0d, 0x93, 0xa4,
	0xe4, 0x52, 0x5a, 0xba, 0x83, 0xdc, 0xd7, 0xc1, 0xd0, 0x9a, 0xef, 0xf1, 0x9b, 0x1c, 0x12, 0xbe,
	0x1e, 0xd6, 0xa3, 0x6e, 0x3d, 0x6b, 0x67, 0xab, 0x1b, 0x32, 0xc7, 0x93, 0x2d, 0x54, 0xa5, 0xb4,
	0xc6, 0x0e, 0x72, 0x47, 0x41, 0xdf, 0x98, 0x5f, 0xf0, 0xa4, 0x28, 0x45, 0xcc, 0xad, 0x89, 0x83,
	0xdc, 0x99, 0xf7, 0x8e, 0xf6, 0x72, 0xb4, 0x95, 0xa3, 0x37, 0x39, 0xfa, 0x1d, 0x44, 0xee, 0x8f,
	0x4f, 0x17, 0x5b, 0x0b, 0x7a, 0xda, 0xfc, 0x86, 0xa7, 0x39, 0xdf, 0xab, 0x75, 0xa8, 0x2c, 0xa3,
	0x0b, 0x2e, 0x68, 0xef, 0x47, 0x07, 0x3f, 0xfa, 0x7b, 0xf0, 0xf3, 0x5f, 0xb5, 0xc9, 0xe3, 0x9d,
	0x8d, 0x02, 0xa3, 0x0d, 0xad, 0x94, 0xff, 0xf7, 0xf4, 0x40, 0xb4, 0x7f, 0x0d, 0xd1, 0x4e, 0x0d,
	0x41, 0xe7, 0x86, 0xa0, 0xfb, 0x86, 0xa0, 0xe3, 0x95, 0x68, 0xe7, 0x2b, 0xd1, 0xfe, 0x5f, 0x89,
	0xf6, 0xe7, 0x6b, 0x2a, 0xd4, 0xb6, 0x8a, 0x68, 0x0c, 0x19, 0x1b, 0x3e, 0xf1, 0x09, 0x36, 0x1b,
	0x11, 0x8b, 0x70, 0xc7, 0xb6, 0x55, 0xc4, 0xea, 0xa5, 0xc7, 0xf6, 0x2f, 0x7f, 0xa8, 0x0e, 0x05,
	0x97, 0xac, 0xf6, 0x22, 0xa3, 0xbb, 0xe2, 0xf3, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x56,
	0xd0, 0x75, 0xec, 0x01, 0x00, 0x00,
}

func (m *Payout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Payout) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Payout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.NextAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.NextAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintPayout(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPayout(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Hours != 0 {
		i = encodeVarintPayout(dAtA, i, uint64(m.Hours))
		i--
		dAtA[i] = 0x20
	}
	if len(m.NodeAddress) > 0 {
		i -= len(m.NodeAddress)
		copy(dAtA[i:], m.NodeAddress)
		i = encodeVarintPayout(dAtA, i, uint64(len(m.NodeAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintPayout(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintPayout(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPayout(dAtA []byte, offset int, v uint64) int {
	offset -= sovPayout(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Payout) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovPayout(uint64(m.ID))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovPayout(uint64(l))
	}
	l = len(m.NodeAddress)
	if l > 0 {
		n += 1 + l + sovPayout(uint64(l))
	}
	if m.Hours != 0 {
		n += 1 + sovPayout(uint64(m.Hours))
	}
	l = m.Price.Size()
	n += 1 + l + sovPayout(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.NextAt)
	n += 1 + l + sovPayout(uint64(l))
	return n
}

func sovPayout(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPayout(x uint64) (n int) {
	return sovPayout(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Payout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayout
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Payout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Payout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayout
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayout
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayout
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayout
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayout
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayout
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayout
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hours", wireType)
			}
			m.Hours = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayout
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Hours |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayout
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPayout
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPayout
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayout
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPayout
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPayout
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.NextAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPayout(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPayout
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPayout(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPayout
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayout
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayout
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPayout
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPayout
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPayout
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPayout        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPayout          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPayout = fmt.Errorf("proto: unexpected end of group")
)
